name: Windows build & release

on:
  push:
    tags:
      - '*'
  
jobs:
  build:
    runs-on: 'windows-latest'

    steps:
    - uses: actions/checkout@v4
    - name: Setup Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install pipenv
      run: |
        pip install pipenv
        pipenv install --dev

    - name: Build executable
      run: pipenv run pyinstaller build-win.spec

    - name: Create ZIP archive
      run: Compress-Archive -Path ./dist/wunderland-generator.exe -Destination ./dist/wunderland-generator.zip

    - name: Release ZIP archive
      uses: softprops/action-gh-release@v1
      with:
        files: ./dist/wunderland-generator.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
